meshtastic/protobufs

mesh.proto
Previous naming was misleading.
Requires updating device code.
=> Make oneOf property naming consistant

mesh.proto
A fix to change the link to the new location for the encryption commentary.
=> Website encryption fix

admin.proto, apponly.proto, channel.proto, deviceonly.proto, environmental_measurement.proto, mesh.proto, mqtt.proto, portnums.proto, radioconfig.proto, remote_hardware.proto
This PR is to add the required parameters (`option go_package`) to the existing Protobufs to allow Go code to be generated. The code changes are very small and consist of adding `option go_package = "github.com/meshtastic/gomeshproto"` to each `.proto` file to allow for `protoc` to generate the required files. 
One thing to note is I chose `github.com/meshtastic/gomeshproto` as an arbitrary package name since there isn't currently a package for any compiled protobuf files that I could find. This shouldn't cause any issues in projects because developers using the Protobuf files for Go could 1) compile the files and then move them to be a local package in their project or 2) setup a `replace` directive in `go.mod` to point to the files at `github.com/meshtastic/gomeshproto`. 
I'm hoping it …
=> Add Options For Go Protobuf Generation

radioconfig.proto
Added GPS coordinate format options for Google's Open Location Codes and the United Kingdom's Ordnance Survey Grid Reference System.
=> Added Plus Codes and OS Grid Reference

mesh.proto
Custom DIY device based on @NanoVHF schematics: https://github.com/NanoVHF/Meshtastic-DIY/tree/main/Schematics
Configuration to meshtastic-device `platformio.ini` and `configuration.h` is upcoming.
=> Custom DIY device hardware model identifier based on @NanoVHF schematics

radioconfig.proto
At the request of some users (mostly on the discord group) having issues with device sleeping in some instances where the battery ADC is not reliable enough to be trusted, I'm proposing this user preference to circumvent the logic in powerFSM.cpp (which I will create another PR for). 
I have personally used this in the form of a #define ALWAYS_POWERED, but I've seen enough interest in it that I feel it deserves a spot in the user preferences.
=> Add is_always_powered user preference

mesh.proto
Adds 3 new fields to the USER object (the basis of the NODEINFO message), which describe the output power of a mesh node: the TX power, the antenna gain and the beam direction.
The fields are optional and their purpose is informative, to assist ad-hoc network discovery, testing and navigation.
=> add node output power info fields

radioconfig.proto
The intention being if this is set >0, a node will power off this long after being disconnected from power (or this long after being turned on when on battery)
=> Add on_battery_shutdown_after_secs preference

mesh.proto
Originally discovered in https://github.com/meshtastic/Meshtastic/pull/160/commits/1ffa55d39a8270686c8ba087634d31826c0f4a33
https://www.kb6nu.com/ham-ham-radio-ham-radio-amateur-radio/#:~:text=Of%20course%20either%20term%20may,be%20avoided%20at%20all%20costs.
=> Ham, not HAM

mesh.proto
no longer in production
This is the protobuf part for the missing older Heltec Board.
=> Add original Heltec V1 board

radioconfig.proto
Feature: add disable_tx setting Meshtastic-device#1065
=> Disable TX from the LoRa radio. Useful for hot-swapping antennas

radioconfig.proto
If you run your own mqtt broker and want to consume meshtastic traffic in another application, it'd sure be easier if the protobufs were decrypted on device first.  We should have a switch to allow this to happen.
The way this is worded will mean that if you connect your device to a custom mqtt broker, upon performing this update on your device, it will by default decrypt protobufs going to mqtt.  This is a change from current behaviour.  
It should not affect mesh bridging over mqtt either way.
=> Add a user preference to control MQTT encryption

radioconfig.proto
Pin Definition names are more generic now so they can be used for other wired input devices. It's very unlikely a device will have more than one of those active at the same time. There's a companion PR in -device that will update the code to work with these changed definitons.
=> Changes for inputbroker modules re-using IO Pins from rotEnc1.

deviceonly.options, deviceonly.proto
This adds Protobuf space in a separate file for an OEM Screen and logo during boot
=> Add storage for OEM screen text and logo

radioconfig.proto
Support for low rate baud rates for use of old electric typewriters with a serial port like Brother EP-44 as a Meshtastic messaging device.
=> Brother EP-44 support

mesh.proto
Can be used for development and definitions on all variants (Stack, Stick, Core, Core2, Epaper, Stamps)
=> Add a major identifier for m5stack hardware.

apponly.proto, deviceonly.proto, localonly.proto
- Add `LoraConfig` to `apponly.proto` `ChannelSet` since it is no longer part of the primary channel.
- Create `localonly.proto` for protos common to `apponly.proto` and `deviceonly.proto`. This is never sent over the wire, only for local use. `LocalConfig` & `LocalModuleConfig` can store combined `Config` & `ModuleConfig` oneofs.
> [AppOnly Proto Needs Refactor for 1.3](https://github.com/meshtastic/Meshtastic-protobufs/issues/155)
=> Issue #155 - proto needs refactor for 1.3 clients

mesh.proto
B&Q Consulting Station Edition G1 hopes to use the number 45 as HardwareModel enum, if it is possible.
About the Station G1:
The Station Edition series is a compact Lora device with high power PA (Maximum TX Power: 35dBm@915MHz or 868MHz for Station G1 Edition), Rugged SMA Antenna Socket, rich external IO interface, wide input voltage range (8VDC-20VDC). 
More Information:
https://uniteng.com/wiki/doku.php?id=meshtastic:station
=> 'STATION_G1'

module_config.proto
This PR removes an unused import that causes an error when generating code from protobufs using protoc.
=> removal of unused import causing error in protoc

localonly.proto, mesh.proto, module_config.proto, telemetry.proto
plus restore hardware enum to put less used hardware at 32+
fixes #197
=> fix linter errors in protobuf setup

portnums.proto
I would like to have a dedicated PortNum for simulating multiple instances of the Linux native application. See also my [PR in Meshtastic-device.](https://github.com/meshtastic/Meshtastic-device/pull/1737)
=> Request PortNum for Simulator App

channel.options, channel.proto, config.options, config.proto
`channel_num` defines the LoRa channel frequency.
- one single `lora.channel_num` users can choose for the LoRa frequency (and QR codes);
- simplifies channel logic, making primary/secondary channel roles/index/order irrelevant.
note: when unset device still picks a random `channel_num` based on the primary channel hash (no change).
not a breaking change.
=> move channel_num to LoRaConfig

device_metadata.proto
This would give any clients the ability to immediately know whether display of the Shutdown button or any Wifi settings is relavent for the connected device.
=> Add canShutdown and hasWifi

mesh.proto
This can also be used as the "stamp" in custom implementations marketed under the Wireless Shell v3
=> Heltec Wireless Stick Lite with ESP32-S3 CPU

mesh.options, mesh.proto
Send amount of available places in the queue as well as last allocation result.
Signed-off-by: Pavel Boldin <pavel.b@techspark.engineering>
=> FromRadio: add QueueStatus payload

mesh.proto
https://betafpv.com/products/elrs-micro-tx-module
Add BETAFPV ELRS Micro TX Module 2.4G with ESP32 CPU
=> Add  BETAFPV ELRS Micro TX Module 2.4G with ESP32 CPU

meshtastic/device_metadata.proto
This is to facilitate more easily accessible information about the node for mapping purposes
=> Add device role and position flags to metdata

meshtastic/config.proto
This will bridge the rather large gap in link budget (6db) and throughput between Long Fast and Long Slow
=> Add new Long Range - Moderately Fast preset

meshtastic/admin.options, meshtastic/admin.proto
=> Admin message to setup node for amateur radio usage

meshtastic/admin.proto, meshtastic/apponly.proto, meshtastic/cannedmessages.proto, meshtastic/channel.proto, meshtastic/config.proto, meshtastic/connection_status.proto, meshtastic/device_metadata.proto, meshtastic/deviceonly.proto, meshtastic/localonly.proto, meshtastic/mesh.proto, meshtastic/module_config.proto, meshtastic/mqtt.proto, meshtastic/portnums.proto, meshtastic/remote_hardware.proto, meshtastic/rtttl.proto, meshtastic/storeforward.proto, meshtastic/telemetry.proto, meshtastic/xmodem.proto
- fix connection_status.proto `java_outer_classname`
- remove deprecated "_optimize_for = LITE_RUNTIME_"
=> fix connection_status java_outer_classname

meshtastic/config.proto
Needed to be done a long time ago, but we _really_ need it to satisfy the FCC's callsign announcement interval policy of stations identifying themselves at least every 10 minutes
=> Added configurable node info interval

meshtastic/mesh.proto
Fairly simple, this just adds a new type to the hardware types in mesh.proto for the [BetaFPV Nano 900 TX](https://betafpv.com/products/elrs-nano-tx-module)
> [Related Issue](https://github.com/meshtastic/protobufs/issues/313)
=> Add Hardware Type: BetaFPV 900 Nano TX

meshtastic/mesh.options, meshtastic/mesh.proto
Add channel to NodeInfo to reach nodes directly that are not listening on out primary channel
=> add channel to NodeInfo

meshtastic/clientonly.options, meshtastic/clientonly.proto
This would allow clients to share a common strongly typed data structure for serializing / deserializing a device profile (names, channels, config, module config) so that it can be consistently used across platforms. 
I'm working on the export functionality as yaml in the C# cli currently.
=> Clientonly protobufs as a device profile contract

meshtastic/module_config.proto
In working on the CalTopo (APRS) integration, I discovered some _quirks_ about how they accept NMEA sentences that we'll have to work around by using this custom mode. 
I will be sending a note to their engineers to hopefully enhance their support by removing some of the limitations
=> CalTopo serial mode

meshtastic/mesh.proto
max_channels: No sense in keeping something that is always hardcoded to 8 in the firmware anyway and macro is used instead
message_timeout_msec: Initialized to a macro value and then the macro value is used everywhere in the codebase 🙄 
has_wifi: This should be sourced from devicemetadata.haswifi now (which also comes up on want_config)
=> Deprecate MyNodeInfo fields: max_channels, message_timeout_msec, has_wifi, channel_utilization, and air_util_tx

meshtastic/portnums.proto
We never use this portnum, because MqttClientProxyMessages exist on FromRadio and ToRadio instead of a MeshPacket
=> Removing Portnum we didn't actually use

meshtastic/mesh.proto
Fix unmappable character (0x98) for encoding windows-1251
> [Related Issue](https://github.com/meshtastic/protobufs/issues/373)
=> Fix unmappable character (0x98) for encoding windows-1251 #373

meshtastic/config.proto
Probably add this to the stack of things to just blow away in 2.2.
=> Deprecate unused mesh_sds_timeout_secs

meshtastic/admin.proto, meshtastic/channel.proto, meshtastic/deviceonly.options, meshtastic/deviceonly.proto, meshtastic/mesh.options, meshtastic/mesh.proto
On the device, we will incremement the DEVICESTATE_VERSION, so folks will need to re-provision their devices. This also gives you all on the app / client front a clean slate. Most of this is removing, _not re-indexing_ deprecated protobufs. We'll save re-indexing for 3.0, since that will be a breaking change for the protocol. Clients need to source some of the removed fields from MyNodeInfo on DeviceMetadata now
This shouldn't be a breaking change, per-se except for the device which as I mentioned will incremement the DEVICESTATE_VERSION and reprovision.  Some clients may respond differently to the removal of protobuf fields, so I'm not entirely sure how that looks in each one. In any account, apps / clients will need to do the minimum version prompt when attempting to pair 2.0/2.1x …
=> 2.2.X Proposed Protobuf changes

meshtastic/admin.proto, meshtastic/config.proto, meshtastic/localonly.proto, meshtastic/mesh.proto, meshtastic/module_config.options, meshtastic/module_config.proto
I've come to the realization that the remote hardware module is just not user friendly at all, and I don't believe it ever will be. This is my solution for the increasing number of folks wanting a simple way to setup PIR motions sensors, reed switches, rain sensors etc that have simple on/off states. This will allow a user to assign a friendly name and gpio pin to monitor for the state change message. I also think, like most modules we can auto-detect a small curated list of i2c based sensors like RAK's human presence radar sensor for instance and utilize those automatically as well.
=> New Detection Sensor module for messaging the mesh on detected state changes

meshtastic/config.proto
A user can add a GPS powered by a transistor controlled by an enable pin. This adds a configuration to set that pin.
=> Adds gps_en_able to indicate GPS enable pin, or 0 for none

meshtastic/mesh.proto
For https://github.com/meshtastic/firmware/pull/2882 to encompass more EBYTE modules without requiring adding future variants
=> Generalize E22-900M_S3 to EBYTE_ESP32-S3

meshtastic/module_config.proto
For the T-Watch S3, T-Deck, and presumably future Lilygo products with i2s audio interface, we can use the esp8266 audio library to do RTTTL ringtone alerts like we do with a pwm buzzer. We need the ability to turn it off / on though.
=> Ext. Notification use i2s audio interface as buzzer

meshtastic/config.options
WiFi PSK can be 256 bits = 32 Bytes and can be represented by a 64 character long hexadecimal string
The size of the variable must be 65 bytes to hold the string and the trailing \0
=> Changed the variable length of wifi_psk

meshtastic/deviceonly.proto, meshtastic/mesh.proto
Closes #404 
This will allow us to know (and store) what each Node's role on the mesh is. I believe it could be helpful information for determining topology along with Neighbors module.
=> Add role to NodeInfo/Lite

meshtastic/config.proto
Closes #408 on the protobufs side and also adds a new ClientHidden role for more signal disciplined usage.
=> Added client-hidden and lost-and-found roles

meshtastic/config.proto
=> Deprecate GPS attempt time

meshtastic/mesh.proto
If we move all Store & Forward logic to `STORE_FORWARD_APP` portnum we can remove the `delayed` field and free up some `MeshPacket` space.
=> deprecate `MeshPacket.delayed`

meshtastic/mesh.proto
This PR is the start of adding the Chatter 2 board to Meshtastic
this is a continuation of the Issue:
[Board]: reconsideration of the chatter 2.0 #2896 
I have debugged the code needed to add this to Meshtastic and am trying to follow the procedure to add a new board.
So this adds the definition in mesh.proto as the first step.
=> update mesh.proto to add CircuitMess Chatter 2

meshtastic/config.proto, meshtastic/mesh.proto
This adds a `via_mqtt` tag to the MeshPacket, which indicates whether a packet has passed via MQTT anywhere on the path towards a node. Furthermore, it adds a `ignore_mqtt` option to the LoRa config, to allow users to ignore packets that came via MQTT somewhere. I specifically chose the LoRa config, because it is to ensure packets only arrive via LoRa.
The `via_mqtt` tag can also be used to show on a Traceroute that it didn’t go purely via LoRa if you don’t want to ignore MQTT.
See https://github.com/meshtastic/firmware/pull/3117.
=> Add `via_mqtt` tag to MeshPacket and `ignore_mqtt` to LoRa config

meshtastic/config.proto
Deprecate the old bool and migrate in the NodeDB?
=> Triple state GPS mode

meshtastic/mesh.proto
> [Board proposal](https://github.com/meshtastic/firmware/issues/3148)
=> add Heltec Wireless Paper V1.0 to HardwareModel

meshtastic/atak.options, meshtastic/atak.proto
Ended up needing another property on the message for proper routing within ATAK
=> Add device callsign

meshtastic/config.proto
Add 923MHz band for Singapore.
Regulatory reference: https://www.imda.gov.sg/-/media/imda/files/regulation-licensing-and-consultations/ict-standards/telecommunication-standards/radio-comms/imdatssrd.pdf band 30d.
> [Related Issue](https://github.com/meshtastic/firmware/issues/3159)
=> Add Singapore Region

meshtastic/atak.options
Firmware doesn't like non-fixed size strings for what we're doing with the ATAK plugin
=> Add length to GeoChat.to

meshtastic/storeforward.options, meshtastic/storeforward.proto
This will replace the currently unused "empty" variant of the StoreForward message to "text", such that clients know how to handle the history from the server. Technically a breaking change, but the "empty" variant was not used in the firmware. 
Also updated some of the comments of other fields.
=> StoreForward: replace "empty" by "text" and improve comments

meshtastic/storeforward.proto
When the S&F router is sending history, the `to` will always be set to the client requesting it, even if it was a broadcast message. With these tags, a client knows whether the original message was actually a direct message or a broadcast.
=> StoreForward: add `TEXT_DIRECT` and `TEXT_BROADCAST` RequestResponse tags

meshtastic/config.proto
Add new device role descriptions to protobuf comments to help developers working on apps.
=> Add new device role descriptions to protobuf comments

meshtastic/mesh.proto
changing the `HardwareModel` enum name is a breaking change for Android.
=> revert `HardwareModel` enum name change

meshtastic/config.proto
This role is for standalone tracker Meshtastic devices (no phone/EUD) in a TAK system.
=> Add TAK_TRACKER role

meshtastic/mesh.proto
Update the comments - looks like these FIXMEs got fixed. The fields are declared as `fixed32` now.
=> Remove fixed FIXME in mesh.proto

meshtastic/mesh.proto
<html><body>
<h3 dir="auto">Description</h3>
<p dir="auto">Meshtastic
Mesh Device Station G2 is an upgraded design of Station G1, using the 
latest ESP32 S3 MCU. As an RF research project, Station G2 also brings 
key updates in RF. The primary RF design goal of Station G2 is to 
improve the Lora receiving sensitivity by about 4dB based on <a href="https://wiki.uniteng.com/en/meshtastic/station-g2#ultra-low-noise-figure-lna-for-lora" rel="nofollow">a dedicated Ultra-Low Noise Figure LNA</a>. And to increase the transmit power and improve Signal to Noise ratio of short data packets by designing the <a href="https://wiki.uniteng.com/en/meshtastic/station-g2#fast-transient-dc-dc-for-lora-power-amplifier" rel="nofollow">Fast-Transient DC-DC for 35dBm Lora PA</a>.</p> <p dir="auto">For Lora …
=> Station G2

meshtastic/mesh.proto
Reverts the comment to it became garbled in https://github.com/meshtastic/protobufs/commit/0221e83d689f7930ed3e5c474eff4fbb8697efbb.
=> Fix MeshPacket.to comment

meshtastic/mesh.options, meshtastic/mesh.proto
In order to implement RFC https://github.com/meshtastic/rfcs/pull/8 and corresponding firmware issue https://github.com/meshtastic/firmware/issues/3239. 
With this clients can use the following pseudocode when receiving a packet to display routing information:
```
if (hopStart != 0 && (hopStart-hopLimit !=0)):
displayHopsAway(hopStart-hopLimit) 
else: 
displayRSSIandSNR()
```
Note that unlike SNR, the amount of hops is not (yet) in the NodeInfo, but can be updated for each received packet.
=> Add hopStart to MeshPacket

meshtastic/deviceonly.options, meshtastic/deviceonly.proto, meshtastic/mesh.options, meshtastic/mesh.proto
The intent of these changes is to reveal some insights to the user about how the delivery is happening over the mesh per node. 
Clients should be able to inform users if a node was seen over the internet via MQTT, if it's a direct neighbor, or witnessed over one of more hops from other nodes in the mesh.
=> Add via_mqtt and hops_away to NodeInfo/Lite

meshtastic/portnums.proto
This PR removes links to pages in the documentation that no longer exist.
=> Remove Broken Links to Documentation

meshtastic/module_config.proto, meshtastic/mqtt.options, meshtastic/mqtt.proto, meshtastic/portnums.proto
This adds a special `MapReport` message and corresponding settings in the MQTT module config. Related feature request is https://github.com/meshtastic/firmware/issues/3336.
Essentially it makes it easy to periodically report some information about a node (like long/short name, position, region, modem preset) for consumption by a map via MQTT only, such that you don't need to enable uplink on your primary channel.
=> MapReport message and config for MQTT

meshtastic/clientonly.proto
This PR adds an explicit `Heartbeat` message that clients will send to devices to signal that the client is still connected. Currently this is only needed for serial connections, although it is recommended to do this for all connections as this packet will not be sent over the mesh.
While the device will not time out if it hears any packet from the client, adding an explicit message is intended to serve as a reminder to client developers to send keep-alive packets explicitly.
=> Add explicit Heartbeat packet for clients to keep alive (serial) connections

meshtastic/deviceonly.proto, meshtastic/mesh.proto
Favorites will be at the top of the list for client node lists and survive NodeDB cleanups.
Closes #429
=> Add is_favorite to NodeInfo/Lite

meshtastic/admin.proto, meshtastic/deviceonly.proto, meshtastic/mesh.proto, meshtastic/remote_hardware.proto
We need to move this one, because drawing a dependency on deviceonly.proto is no bueno.
=> Move remote hardware pins to sever problematic device_only dependency

meshtastic/mesh.proto
See [PR](https://github.com/meshtastic/firmware/pull/3530) to main meshtastic firmware for more info.
As suggested by dev's I would like to extend the HardwareModel to include the [unPhone](https://unphone.net).
Thanks!
=> Add UNPHONE to mesh.proto HardwareModel enum

meshtastic/mesh.proto
Needed for [adding support for the CDEBYTE_EoRa-S3 variant](https://github.com/meshtastic/firmware/pull/3613).
=> Add CDEBYTE_EORA_S3 to mesh.proto HardwareModel enum

meshtastic/config.proto
Add status_led_off to support turning status LED off (dark mode).
This only affects the GPIO-controllable LED and may be desirable behavior for Meshtastic users who sleep in the vicinity of their node and are annoyed by the blinking LED, especially for boards that indicate charging when USB power is connected, resulting in a 1 second LED illumination cycle.
Most boards however, have a non-GPIO controlled power LED (i.e. hardwired to VBUS/VCC/etc.) that can only be turned off by desoldering or otherwise removing that LED. This can't be addressed by firmware changes.
> [[Feature Request]: Option to turn off LED inducators on ESP32 Heltec V3](https://github.com/meshtastic/firmware/issues/3635)
=> Add status_led_off to support turning status LED off (dark mode)

meshtastic/config.proto
This hopefully calls out that we're not enabling any kind of "dark mode" but rather just turning off of the standard led blinking behavior
=> Rebrand as heartbeat led and add more explicit description

meshtastic/mesh.proto
Add  HardwareModel: TWC_MESH_V4  to mesh.proto HardwareModel enum   
[Add new variant: TWC_Mesh #3705](https://github.com/meshtastic/firmware/pull/3705)
=> add HardwareModel: TWC_MESH_V4 to mesh.proto HardwareModel enum

meshtastic/channel.proto
This will allow the configuration of a "muted" channel to stay with the device, but be enforced on client / apps
Closes #490
=> Added mute channel into module settings

meshtastic/telemetry.proto
This PR implements lux and irradiance measurement with the sensor veml7700, on the protobuf
=> add ligth sensor to the env telemetry module

meshtastic/admin.options
Synchronize ham short_name length with meshtastic user short_name length
Setting the field length of short_name to 5 instead of 6.
The length of the short name of a meshtastic user is 4. 
The array of chars containg the name has the length of 5 (terminating zero at byte 5).
The short name length and the refelcting field of HAM should not exceed these values.
Note: You cannot set the short name of a user to more than 4 chars via the app, so it should not be a vital issue.
=> Synchronize ham short_name length with meshtastic user short_name length

meshtastic/mesh.proto
RadioMaster 900 Bandit Nano ID, https://www.radiomasterrc.com/products/bandit-nano-expresslrs-rf-module
Add an ID for Radio Master Bandit Nano.
- [*] All top level messages commented
- [*] All enum members have unique descriptions
=> Add ID for Bandit Nano

meshtastic/mesh.proto
The mesh.proto file was broken, was missing a semicolon.
See https://github.com/meshtastic/protobufs/actions/runs/9235231619/job/25409808160
=> Fix invalid protobuf

meshtastic/config.proto
We have rudimentary compass support in a branch. This would add a setting to correct the output when the sensor is oriented differently than the screen.
=> Add compass_orientation

meshtastic/mesh.proto
Add Heltec Capsule Sensor V3 definition to `HardwareModel` Enum.
=> Add Heltec Capsule Sensor V3

meshtastic/mesh.proto
A product built around the HT-CT62 module (ESP32-C3 CPU and SX1262 LoRa) and SKUs with various sensors. A separate variant is needed due to re-use of GPIOs for LEDs, user button, power gating to the I2C peripheral, etc.
https://heltec.org/project/hru-3601/
=> Add Heltec HRU-3601

meshtastic/config.proto, meshtastic/powermon.proto
Should be a nop for anyone else (for the time being).  But checking in now (seems pretty stable - probably no big changes coming) so I can soonish propose firmware and python PRs that use this.
for https://github.com/meshtastic/firmware/issues/4136
=> PowerMon initial protobufs

meshtastic/mesh.options, meshtastic/mesh.proto
These will be sent up on want_config flow to inform clients of the device's file system manifest file-by-file.
=> Add FileInfo packet to FromRadio

meshtastic/deviceonly.proto
This change removes an unnecessary import statement in one of the protobuf files. When I generated protos on the Apple clients, I kept getting this message...
```
➜  Meshtastic-Apple (2.3.12_Working_Changes) ✔ ./scripts/gen_protos.sh
meshtastic/deviceonly.proto:8:1: warning: Import meshtastic/module_config.proto is unused.
Done generating the swift files from the proto files.
Build, test, and commit changes.
```
I'd like to figure out if this is an actual issue with the protobuf definitions, or if the codegen is busted.
=> Remove unnecessary import

meshtastic/mesh.proto
Added 4 Heltec New boards.
- Vision Master T190 -- ESP32-S3 CPU, and a 1.90-inch TFT display
- [Vision Master E213](https://heltec.org/project/vision-master-e213/) -- ESP32-S3 CPU, and a 2.13-inch E-Ink display
- [Vision Master E290](https://heltec.org/project/vision-master-e290/) -- ESP32-S3 CPU, and a 2.9-inch E-Ink display
- Mesh Node T114 -- nRF52840 CPU, and a 1.14-inch TFT display, Ultimate low-power design, specifically adapted for the Meshtatic project
=> Add Heltec new boards

meshtastic/module_config.proto
This adds a boolean option to set a node as StoreForward server. 
I think the restriction to set the node as `ROUTER` in order to be a StoreForward server is outdated, especially now that `ROUTER_CLIENT` is deprecated. A node that is good at sniffing packets to store them is not necessarily a good node to hop over. For example, I have a T-Beam in my house that acts as StoreForward server in `ROUTER_CLIENT` role for when I come home with my mobile node, but my RAK on the roof would be much better to hop over.
=> Add bool to StoreForward config to set it as server

meshtastic/config.proto
Disable the build-in PA FAN using pin define in RF95_FAN_EN for use in "Low Traffic" areas where cooling of PA it not necessary.
=> Disable PA FAN

meshtastic/config.options, meshtastic/config.proto, meshtastic/localonly.proto, meshtastic/mesh.options, meshtastic/mesh.proto
=> Adds public_key and private_key for PKI

meshtastic/mesh.proto
These fit in flash now and at least for the Wio-E5 I confirmed you can configure your region with the userPrefs file to send and receive messages.
=> Add RAK3172 and Wio-E5 STM32WL-based hardware models

meshtastic/telemetry.proto
This adds enums for new sensor types in the Telemetry module:
- BMP3XX - high accuracy temperature and pressure (n.b. an upgrade from BMP-280)
- ICM-20948 9-Axis digital motion processor (n.b. an upgrade from MPU-6050)
- MAX17048 1S lipo battery sensor provides voltage, state of charge, and time to go (n.b. gives the rate of discharge which is great for battery powered devices)
There is no impact or changes to existing sensors
Appreciate if you can merge this PR into the mestastic protobufs, and I'll raise another for the meshtastic firmware to add these new sensors to the Telemetry module
=> Additional Telemetry sensors - BMP388, ICM-20948, MAX17048

meshtastic/deviceonly.options, meshtastic/deviceonly.proto
Really we're just getting rid of User.id, which is not insignificant in terms of savings. I initially got rid of macaddr but upon implementation, it was too involved, and I bailed.
=> User -> UserLite in NodeDB

meshtastic/mesh.proto
This error message should be interpreted as not an error, and also as an indicator that an outgoing message was sent via PKI.
=> Add NONE_PKI error message

meshtastic/admin.options, meshtastic/admin.proto
Adds a session passkey for admin operations. When the remote node responds to any get_x request, it will include the session passkey in the response. When the local client tries to make any admin changes, the remote node expects that session key to be set. The session key will expire after a short time, currently 120 seconds.
=> Adds Admin session_passkey to prevent replay of admin packets

meshtastic/mesh.options, meshtastic/mesh.proto, meshtastic/portnums.proto
In order to get two-way information with SNR per hop in a traceroute, this adds another list of nodenums `route_back` and two lists of 1-byte SNR values (in dB, but scaled by 4, so e.g. a value of -64 is -16dB), namely `snr_towards` and `snr_back`.
This should allow us to visualize a traceroute from node 0x10 to 0x13 as:
```
0x10 --> 0x11 (-5.00dB) --> 0x12 (-4.00dB) --> 0x13 (7.00dB)
(-5.00dB) 0x10 <-- (-4.00dB) 0x11 <-- (7.00dB) 0x12 <-- 0x13
```
=> Add route back and SNR lists to RouteDiscovery for traceroute

meshtastic/config.proto
security option.  Per discussion in https://github.com/meshtastic/firmware/issues/4375 no need to preserve the old options when changing to this new simpler single boolean because they were newish, rarely used and only for 'advanced' developers.
=> remove and merge  deprecated serial/bt logging options 

meshtastic/config.options, meshtastic/config.proto
We might want to allow multiple admin keys for remote administration. This makes it an easier change to do so if we choose to.
=> Make admin_key repeated max count 1, for future expansion

meshtastic/mesh.proto
For https://github.com/meshtastic/firmware/issues/4576
I considered it calling `TEXT`, but maybe in the future it suits for different portnums as well.
Gave it the value 100 such that there's still some room between `RELIABLE` and `HIGH` (e.g. for `MEDIUM`) and between `HIGH` and `ACK`, e.g. for `CRITICAL`.
=> Add new MeshPacket priority HIGH

meshtastic/mesh.proto
Give a priority which is slightly higher than `RELIABLE` for packets that are a response to a request, because we want it to get there relatively quickly. Furthermore, responses stop relaying packets directed to a node early.
=> Add RESPONSE priority for responses to a request

meshtastic/config.proto, meshtastic/mesh.proto
Implements part of https://github.com/meshtastic/rfcs/blob/position-mqtt-privacy/rfcs/2024-08-30-position-privacy.md. This adds a bit to each data protobuf, indicating that the user consents to uploading their data to a public MQTT broker. Without this bit set to true, for the public channel, the firmware will refuse to upload packets to MQTT, and our MQTT broker will refuse to process the packets.
=> Adds OKToMqtt bool to data

meshtastic/mesh.proto
Most admin authorization problems are just returning a NO_RESPONSE error, which isn't very helpful. This adds a couple of the more likely problem states.
=> More Admin Errors

meshtastic/deviceonly.proto, meshtastic/mesh.proto
convert hops_away from required to optional
This will enable feature work to differentiate between hops_away not available and hops_away is zero
=> convert hops_away from required to optional

meshtastic/mesh.proto
Hitting an odd case with clients, that don't realize old nodes don't support Public Key DMs.
=> Adds the hasPKC bool to device metadata capabilities

meshtastic/clientonly.options, meshtastic/clientonly.proto
adds `fixed_position`, `ringtone`, and `canned_messages` fields to `DeviceProfile` for export/import functionality.
=> add fixed_position, ringtone, and canned_messages to `DeviceProfile`

meshtastic/module_config.options, meshtastic/module_config.proto
Add support for meshtastic/firmware#4753, see meshtastic/firmware#4776 for additional context
`DetectionSensorConfig.detection_trigger_type` supersedes `detection_triggered_high` keeping same tag because both bools and enums are internally represented as varints
=> Implement more flexible triggering in DetectionSensor

meshtastic/telemetry.proto
Some more statistics to get insight in the routing performed by your node and nodes around you.
=> Add more packet statistics to LocalStats

meshtastic/telemetry.proto
Mentioned in https://github.com/meshtastic/firmware/issues/4738 as being most appropriate for sensing animal temperature. 
Also, according to https://www.sparkfun.com/products/retired/14569, a replacement for the apparently retired MLX90632
=> Add MLX90614 non-contact IR temperature sensor.

meshtastic/module_config.proto
health_screen_enabled will be used for turning on/off the screen for health telemetry.
Also fixed some commands on other existing variables that were incorrect.
=> Add health_screen_enabled and fix comments

meshtastic/admin.proto, meshtastic/device_ui.options, meshtastic/device_ui.proto, meshtastic/mesh.proto
Added
- device-ui proto+options with persistent data for all settings
- admin config get/set for device-ui data
- mesh proto change to send ui data during PhoneAPI initial connect
=> Add device-ui persistency

meshtastic/deviceonly.options, meshtastic/deviceonly.proto
belongs to https://github.com/meshtastic/firmware/pull/5061
=> remove oem.proto

meshtastic/config.proto
Enables a bit more traffic management on the mesh. This will essentially unlock what we did for EVENT_MODE at DefCon as a configuration. IMO, setting the Role of Repeater or Router should default to this once implemented in order to curb over-utilization of preferred routers with non-standard traffic.
=> Add rebroadcast mode to ignore non-standard portnum traffic

meshtastic/device_ui.options, meshtastic/device_ui.proto
- add version control to invalidate incompatible changes with proto old files
- add more language options + experimental Chinese language enums
- add persistence parameters for screen/settings lock and message alert
=> device-ui: proto version control, new languages, lock and alert parameters

meshtastic/mesh.proto
adds bit field to `DeviceMetadata` for tracking excluded modules
=> add bit field to `DeviceMetadata` for excluded modules

meshtastic/module_config.proto
As discussed in https://github.com/meshtastic/firmware/issues/5082.
This will default to false. Only needs to be enabled when NeighborInfo from remote nodes is wanted.
=> Add bool to enable LoRa transport for NeighborInfo

meshtastic/admin.proto, meshtastic/deviceonly.proto, meshtastic/mesh.proto
Adds an `is_ignored` flag to the NodeInfo structs. This can be set and unset with admin messages just like the current `is_favorite` flag. This flag is for adding support for ignoring packets from nodes, like the `ignore_incoming` array but without being limited to 3 entries.
I will attempt to create a matching pull request in the firmware project for the firmware-side changes.
> [Related Issue](https://github.com/meshtastic/firmware/issues/5297)
=> Add is_ignored bool field to NodeInfo

meshtastic/device_ui.options, meshtastic/device_ui.proto
- store calibration data (8x int16)
- added enum for Norwegian language translation
=> device-ui update: store calibration data, added enum Norwegian language translation

meshtastic/deviceonly.options, meshtastic/deviceonly.proto, meshtastic/mesh.options, meshtastic/mesh.proto
These are the required additions for https://github.com/meshtastic/firmware/pull/2856.
It adds the `next_hop` and `relay_node` byte to the MeshPacket, which are used only by the firmware. Furthermore, the `next_hop` will be stored per node in the NodeDB on the device.
=> Required additions for NextHopRouter

meshtastic/telemetry.proto
This PR is to support the [ClimateGuard RadSense dosimeter](https://github.com/climateguard/RadSens/blob/master/extras/datasheets/RadSens_datasheet_ENG.pdf).
This is an I2C device which integrates nicely into the firmware along side other sensors.
- Added `radiation` to `EnvironmentMetrics` to hold the measurement in micro-roentgen
- Added `RADSENS` to `TelemetrySensorType`
These changes will support a future pull request to the meshtastic firmware to add support for this device.
Thanks for your consideration.
=> Support for the ClimateGuard RadSens Geiger-Muller tube

meshtastic/mesh.options, meshtastic/mesh.proto, meshtastic/storeforward.options
Updates `DATA_PAYLOAD_LEN` and .option fields to 233 bytes to reflect the new `Data` length limit due to added fields.
=> update payload max length

meshtastic/mesh.proto
Allow to differentiate nodes running my own implementation VS meshtastic's code.
=> add Routastic hardware model

meshtastic/config.proto, meshtastic/mesh.proto
This PR adds the new ~`ROUTER_INFILL`~ `ROUTER_LATE` role & supporting fields for the following firmware PR:
https://github.com/meshtastic/firmware/pull/5528
=> Add the ROUTER_LATE role & supporting fields

meshtastic/device_ui.options, meshtastic/device_ui.proto
- add persistency config for filter by channel number
- add Slovenian language enum
=> device-ui: add channel filter, add slovenian

meshtastic/mesh.proto
Just added the definition for the new MeshLink board, as discussed here: https://github.com/meshtastic/firmware/pull/5736#discussion_r1903236576
=> Added definition for MeshLink board

meshtastic/module_config.options, meshtastic/module_config.proto
MQTT config is currently bigger than the LoRA MTU. Needs to shrink
=> Mqtt shrink

meshtastic/admin.proto, meshtastic/config.proto, meshtastic/deviceonly.proto, meshtastic/mesh.proto
- Move nodedb to it's own message (and file)
- UDP meshing over the LAN for ESP32 devices
=> 2.6 changes

meshtastic/telemetry.proto
Adds an enum value for the [DPS310](https://www.infineon.com/dgdl/Infineon-DPS310-DataSheet-v01_02-EN.pdf?fileId=5546d462576f34750157750826c42242) 24-bit pressure sensor.
=> telemetry: add dps310

meshtastic/portnums.proto
Add a port number reservation for Reticulum tunneling over meshtastic. The new portnum is intended to reduce chance of interference with other private apps.
Reticulum is a network stack/protocol which allows users to create low bandwidth networks over a variety of interface types. These features include, messaging, remote terminal execution, file transfers, audio messages, audio calls, etc and using the python library, these features can be used to create new network applications such as [meshchat](https://github.com/liamcottle/reticulum-meshchat). 
Since Meshtastic doesn't support these features, and RNode (reticulum firmware), isn't as versatile as Meshtastic firmware, bridging RNS over Meshtastic becomes desirable.  
[RNS_Over_Meshtastic](https://github.com/landandair/RNS_Over_Meshtasti …
=> Add new Portnum 76 for Reticulum Network Stack Tunnel App

meshtastic/telemetry.options, meshtastic/telemetry.proto
As per @Justin-Mann , the RAK12035 is a Soil Moisture Sensor made by RAKWireless. Up to three can be connected using the wisblock architecture.
Co-Authored-By: @Justin-Mann
=> Add RAK12035VB Soil Moisture Sensor

meshtastic/admin.proto
Our Rust clippy linter hit this error when we've updated to fresh protobufs:
```
$ cargo clippy -- -D warnings
error: empty doc comment
--> src/generated/meshtastic.rs:6366:9
|
6366 | /         ///
6367 | |         ///
| |___________^
|
= help: consider removing or filling it
```
=> Fix empty doc to satisfy picky linters

nanopb.proto
Adds the go_package output path to nanopb.proto to match the other .proto files and fix protobuf build errors.
Adds the go_package output path to nanopb.proto to match the other .proto files and fix protobuf build errors.
=> Add go_package path for nanopb.proto

meshtastic/mesh.proto
Added Heltec new product [MeshPocket](https://heltec.org/project/meshpocket/) board definition.
=> Add Heltec MeshPocket definition

meshtastic/telemetry.proto
Add [MAX17261](https://www.analog.com/media/en/technical-documentation/data-sheets/max17261.pdf) lipo battery gauge
=> Add MAX17261 lipo battery gauge

meshtastic/telemetry.proto
We can't predict what information a user might want to send with the HostMetrics message, so provide an optional arbitrary string for the purpose.
=> Add the user_string to HostMetrics

meshtastic/telemetry.proto
This PR adds a definition for the PCT2075 temperature sensor
This relates to https://github.com/meshtastic/firmware/pull/6829
=> Add PCT2075 sensor

meshtastic/deviceonly.proto, meshtastic/mesh.proto
Adds a nodeinfolite bitfield, and defined the LSB 0 as is_manually_validated
=> add nodeinfo bool/bitfield for is_manually_validated

meshtastic/mesh.proto
Add GAT562 Mesh Trial Tracker HW model ID
> [Related Issue](https://github.com/meshtastic/firmware/pull/6984)
=> Add GAT562 Mesh Trial Tracker HW model ID

meshtastic/config.proto
As reported by @monkeypants, the MY_433 region is not legal in ANZ due to power limits being too high. This patch introduced an ANZ_433 region to match the requirements in Australia and New Zealand.
433.05 - 434.79 MHz, 25mW EIRP max, No duty cycle restrictions AU Low Interference Potential https://www.acma.gov.au/licences/low-interference-potential-devices-lipd-class-licence NZ General User Radio Licence for Short Range Devices https://gazette.govt.nz/notice/id/2022-go3100
Fixes https://github.com/meshtastic/firmware/issues/7032
=> Add ANZ_433 Region

meshtastic/portnums.proto
Add support for Cayenne Low Power Payload popular in LoRaWAN. This has benefit of removing burden to specify every conceivable telemetry type in telemetry.proto while still relying on well defined telemetry/data types from Open Mobile Alliance (OMA) / IPSO Alliance (or fully custom ones according to IPSO alliance numbering scheme)
Also enables very constrained sensor nodes that are not capable of building bigger / nested protobuf structures (in contrast to protobuf in protobuf encoding like telemetry.proto / telemetry app)
Some references: 
- https://docs.mydevices.com/docs/lorawan/cayenne-lpp
- https://www.thethingsindustries.com/docs/integrations/payload-formatters/cayenne/
- https://www.openmobilealliance.org/specifications/registries/objects
=> Add PortNum for Cayenne Low Power Payload

meshtastic/config.proto
Add `DIRECT_MSG_ONLY` option for BuzzerMode.
Allow the user to set external notifications to only buzz upon Direct Messages.
=> Add DIRECT_MSG_ONLY Buzzer mode

meshtastic/telemetry.proto
This PR adds SFA30 device and associated metrics to support data logging of [HCHO](https://en.wikipedia.org/wiki/Formaldehyde) with electrochemical sensors by Sensirion. Done by @Nikl174.
=> Added formaldehyde sensor values sfa30

meshtastic/telemetry.proto
An additional sensor type to be able to support two ADS1X15 sensors in parallel. Goes with https://github.com/meshtastic/firmware/pull/7109
=> Add additional telemetry sensor type to support two ADS1X15s

meshtastic/config.proto
As identified by @WOD-MN , Nepal has a dedicated IoT frequency.
865 MHz to 868 MHz, no power limit, not duty cycle restrictions
Machine to Machine (M2M)/Internet of Things (IoT)  https://www.nta.gov.np/uploads/contents/Radio-Frequency-Policy-2080-English.pdf
Firmware patch: https://github.com/meshtastic/firmware/pull/7380
=> Add Nepal 865 MHz to 868 MHz

meshtastic/config.proto, meshtastic/mesh.options, meshtastic/mesh.proto, meshtastic/telemetry.proto
It may be useful to the clients to know if the firmware they are connecting to is an event firmware. This gives us an easy place to indicate.
=> Add event enum to indicate to client if this is event firmware

meshtastic/module_config.proto
Includes a configuration option which allow's the toggling of cleanup capabilities for RangeTest results.
See: [https://github.com/meshtastic/firmware/pull/7703](https://github.com/meshtastic/firmware/pull/7703)
=> Rangetest cleanup configuration option

meshtastic/config.proto, meshtastic/device_ui.options, meshtastic/device_ui.proto
- Move GpsCoordinateFormat gps_format and enum GpsCoordinateFormat to Device_UI Protobuf
- Related to "Add Maidenhead Locator implementation"
=> Move GpsCoordinateFormat gps_format And enum GpsCoordinateFormat to Device_UI Protobuf, Add Maidenhead Option

meshtastic/config.proto
Adds an option to protobufs (per comment below) to allow choosing node name lengths when displaying on an OLED display.
I'm not sure if this is complete, or if it is even in the right spot. I could see it living in either `config.proto` or `device_ui.proto`
> Please see this [comment](https://github.com/meshtastic/firmware/pull/7926#discussion_r2331910610) on why this PR is being submitted.
=> add node_name_length option

meshtastic/telemetry.options, meshtastic/telemetry.proto
This is required for https://github.com/meshtastic/firmware/issues/8056.
This number *should* not be too big, so I chose to use 16 bits.
=> Add number of dropped packets to LocalStats

meshtastic/admin.proto, meshtastic/apponly.proto, meshtastic/atak.proto, meshtastic/cannedmessages.proto, meshtastic/channel.proto, meshtastic/clientonly.proto, meshtastic/config.proto, meshtastic/connection_status.proto, meshtastic/device_ui.proto, meshtastic/deviceonly.proto, meshtastic/interdevice.proto, meshtastic/localonly.proto, meshtastic/mesh.proto, meshtastic/module_config.proto, meshtastic/mqtt.proto, meshtastic/paxcount.proto, meshtastic/portnums.proto, meshtastic/powermon.proto, meshtastic/remote_hardware.proto, meshtastic/rtttl.proto, meshtastic/storeforward.proto, meshtastic/telemetry.proto, meshtastic/xmodem.proto
Changes the package name of generated java/kotlin files from `com.geeksville.mesh` to `org.meshtastic.proto`
Relevant draft PR in the Android repo: https://github.com/meshtastic/Meshtastic-Android/pull/3291 
Due to limited availability and ongoing support, new Hardware Models will only be accepted from [Meshtastic Backers and Partners](https://meshtastic.com/). The Meshtastic team reserves the right to make exceptions to this policy.
You are welcome to use one of the existing DIY hardware models in your PlatformIO environment and create a pull request in the firmware project. Please note the following conditions:
- The device will **not** be officially supported by the core Meshtastic team.
- The device will **not** appear in the [Web Flasher](https://flasher.meshtastic.org/) or Github …
=> Change java package to `org.meshtastic.proto`
