- mesh.proto
>  Update comment around use of `modem_config`

- portnums.proto
Adds a portnum definition for the ATAK Forwarder plugin for ATAK
> Add portnum definition for ATAK Forwarder

- environmental_measurement.proto
- portnums.proto
Relates to https://github.com/meshtastic/Meshtastic-device/pull/646
> add environmental measurements

- deviceonly.proto
- mesh.proto
- portnums.proto
- remote_hardware.proto
Only code comment has been changed
> Fix some typo and improve indentation of code comments

- radioconfig.proto
Added options for the GPS formats so that a user can choose between decimal degrees, DMS (degrees minutes seconds), UTM, and MGRS. These match up with what was included in the device code PR for issue #437.
> Added gps coordinate formats.

- radioconfig.proto
Will be accompanied by behavioral code changes to meshastic-device.
> Add auto_screen_carousel_secs preference for automatic screen toggling

- portnums.proto
Add a dedicated port for an experimental plugin I've been working on:
https://github.com/a-f-G-U-C/Meshtastic-ZPS (warning: very draft work)
> add ZPS port

- storeforward.proto
Rename java outer class for SF
> Rename java outer class for SF

- mesh.proto
https://github.com/meshtastic/Meshtastic-device/issues/1034
> Add channel utilization float

- mesh.proto
https://github.com/meshtastic/Meshtastic-device/issues/1035
> Build tapback support into the meshpacket

- admin.proto
> Shutdown admin message

- mesh.proto
ref. https://github.com/meshtastic/Meshtastic-device/pull/1141
if the chosen number is not ideal, feel free to change or improve :-)
> platformio split - private hardware id

- radioconfig.proto
Starting work on the serial plugin. First step: user changeable serial baudrates.
> Add serialplugin_baud

- radioconfig.proto
Add NZ865
See https://github.com/meshtastic/Meshtastic-device/pull/1244
> Added NZ865 Frequency

- radioconfig.proto
> update plugin to module in radioconfig

- radioconfig.options
> update plugin to module in radioconfig.options

- admin.options
- admin.proto
- cannedmessages.options
- cannedmessages.proto
- mesh.options
- mesh.proto
- portnums.proto
- radioconfig.proto
- remote_hardware.proto
> More update plugin to module, mostly cannedmessages

- radioconfig.proto
[Add Role to radioconfig](https://github.com/meshtastic/Meshtastic-protobufs/commit/ecf2862e17da14771d95707fcf8c057e7f37d30e)
> Add Role to radioconfig

- radioconfig.proto
> Rename Unset to Default role

- radioconfig.proto
> Update index for role

- mesh.proto
- portnums.proto
Remove ROUTER_APP and add router_heartbeat to position
> Remove ROUTER_APP and add router_heartbeat to position

- mesh.options
- mesh.proto
> Add router to MyNodeInfo

- mesh.options
> Reduce air_period to 8

- mesh.options
- mesh.proto
- radioconfig.proto
> Remove router implementation from RFC and change over to position_broadcast_smart_disabled

- radioconfig.proto
> remove is_router

- telemetry.proto
> Convert battery level to uint

- mesh.proto
> Add message locations

- radioconfig.proto
Change mode to enum, support proto and change baud to enum
> Change mode to enum, support proto and change baud to enum

- mesh.proto
- radioconfig.proto
- telemetry.options
- telemetry.proto
> Telemetry rework 3

- deviceonly.options
[bump node_db max_count to 80](https://github.com/meshtastic/Meshtastic-protobufs/commit/ae87656930996df30f96fa2152fb329143818f14)
> bump node_db max_count to 80

- radioconfig.proto
> Modify roles

- mesh.proto
> Promote device metrics

- mesh.proto
This is for the new DIY nRF82540 PCA10059 Dongle
> Add DIY nRF82540 PCA10059  to Protocol Buffers

- radioconfig.proto
> Removed pref

- radioconfig.proto
> Removed phone-sds-timeout

- mesh.options
- mesh.proto
[Add compressed payload variant](https://github.com/meshtastic/Meshtastic-protobufs/commit/2946f6e5c374cb2bb9a22ca7bc5fcc5a99bba02e)
> Add compressed payload variant

- deviceonly.options
> reduce max node_db to 64

- mesh.proto
Adds disaster radio's dev board to the protobufs.
> [Related Issue](https://github.com/meshtastic/Meshtastic-device/issues/1442)
> Disaster Radio dev board support

- config.proto
- deviceonly.proto
If this works, do that for the Module Config as well.
Also removes Remove duplicate setting in PositionConfig.
> Define a new object to hold all of our nested config.

- config.proto
Fix for: https://github.com/meshtastic/Meshtastic-device/issues/1308
> Add config to enable hidden access point

- module_config.proto
> Reordered serial_baud indexes

- mesh.proto
- portnums.proto
Rename COMPRESSION_APP to TEXT_MESSAGE_COMPRESSED_APP and flatten the payload variant to get rid of payload compressed
> Compression protobuf changes

- deviceonly.options
> change node_db to 80

- portnums.proto
> Add WAYPOINT_APP

- config.proto
[Removed gps_accept_2d](https://github.com/meshtastic/Meshtastic-protobufs/commit/e64d3a9fbdeb6b5f0d5e361efe88d417eb5f1c02)
> Removed gps_accept_2d

- config.proto
> remove gps_max_dop

- config.proto
- module_config.proto
Comment Cleanup to reduce dependance on the super confusing power state machine page.
As a developer I want to have field documentation stored on that field.
> Clean up Comments

- config.proto
> Remove is_always_powered

- config.proto
Adds speed and heading to the position flags.
Part of https://github.com/meshtastic/Meshtastic-protobufs/issues/165
> Add Speed and Heading to Protobufs for Overlanding functionality

- config.proto
> Fix typo in modem configuration

- config.proto
prerequisite for https://github.com/meshtastic/Meshtastic-device/issues/1595
> Add Bool for WIFI operation

- config.proto
> Power docs update

- config.proto
- module_config.proto
> Add  & swap more fields to enabled by default

- telemetry.proto
> Add 3-axis magnetic force and 6-axis inertial sensor enum

- admin.proto
> Change `get_device_metadata_request` to a boolean

- admin.proto
> Yank `get_all_channel_request`

- admin.proto
- mesh.proto
> Add channel to from radio

- config.proto
> Add a frequency definition for the worldwide 2.4 GHz ISM Range

- config.options
??:??:?? 2 Radio myRegion->numChannels: 416
especially on US region the narrow channels will exceed 256 easily
> allow more than 256 freq slots.

- admin.proto
- apponly.proto
- cannedmessages.proto
- channel.proto
- config.proto
- device_metadata.proto
- deviceonly.proto
- localonly.proto
- mesh.proto
- module_config.proto
- mqtt.proto
- portnums.proto
- remote_hardware.proto
- storeforward.proto
- telemetry.proto
> Update go package name

- config.proto
> remove wifi-mode

- admin.proto
- mesh.proto
> Remove peer info

- mesh.proto
> remove unused `peer-info` field

- mesh.proto
> updated links

- config.proto
- mesh.proto
> Protobuf changes for duty cycle limit

- portnums.proto
See my [PR in firmware](https://github.com/meshtastic/firmware/pull/2026).
> Add TRACEROUTE_APP portnum

- telemetry.proto
Add SHT31 temperature sensor to protobufs
> add SHT31 to protobuf

- config.proto
Numerical values and struct stay the same. May need changes to the client code for setting/getting these
> Rename eth_mode->address_mode, it's also for WiFi

- mesh.proto
> Emoji as a waypoint icon

- mesh.proto
Instead of locked being a boolean, it should be describe who can edit or if all participants of the mesh can
> Change locked to locked_to

- config.proto
> Add Ukraine Freq

- meshtastic/config.options
- meshtastic/config.proto
> add rsyslog server and port

- meshtastic/config.proto
Added tracker and repeater roles
> New device roles and clarification

- meshtastic/config.proto
Add the ability to control how the device rebroadcasts packets
> Added rebroadcast mode to device

- .github/workflows/ci.yml
- .github/workflows/publish.yml
> Fix CI Issues

- .github/workflows/create_tag.yml
> update Relase CI

- meshtastic/mesh.proto
> [Related Issue](https://github.com/meshtastic/firmware/issues/2280)
- [x ] All enum members have unique descriptions
> Add nano g1 explorer

- .github/workflows/create_tag.yml
> please work

- meshtastic/admin.proto
- meshtastic/config.proto
- meshtastic/connection_status.proto
- meshtastic/deviceonly.proto
Improve documentation.
Minor typo fixes. Some readability changes. No technical changes.
- [na ] All top level messages commented
- [na ] All enum members have unique descriptions
> Documentation: Minor typo fixes. Some readability changes

- meshtastic/channel.proto
updated `ChannelSettings` field comments to reflect 2.0 changes
> fix: update ChannelSettings field comments

- meshtastic/module_config.options
- meshtastic/module_config.proto
https://github.com/meshtastic/firmware/issues/2380
> support configurable topic root

- meshtastic/module_config.options
- meshtastic/module_config.proto
Creation of Ambient Lighting Module protobufs in order to control light levels and RGB of the RAK 14001 (and potentially other software controlled LEDs later).
I don't have the related code in the firmware to interact with the protobufs yet, because I don't know how to do that yet :)
- [Y] All top level messages commented
- [N/A] All enum members have unique descriptions
> Ambient Lighting Module protos

- meshtastic/mesh.proto
NANO_G2_ULTRA = 18; has been added for new board.
More info about nano g2 ultra: https://wiki.uniteng.com/en/meshtastic/nano-g2-ultra
> Added Nano G2 Ultra to 18

- meshtastic/mesh.proto
Note: this is going to the `2.2-proposed-changes` branch.
This is needed to remove our neighbors at an appropriate time.
> Add last_rx_time and node_broadcast_interval_secs to Neighbor

- meshtastic/admin.proto
Adds AmbientLightingModule to Admin.proto
> Adds AmbientLightingModule to Admin.proto

- meshtastic/portnums.proto
The lines marked with a (?) need to be confirmed.
> Add hints how the payload of a certain portnum is encoded

- meshtastic/config.proto
> Update to indicate the new default flags

- meshtastic/module_config.proto
- meshtastic/telemetry.proto
Added new telemetry packet variant for power metrics.
Added INA3221 voltage / current sensor.
> Power Metrics Telemetry Variant / INA3221 Sensor

- meshtastic/config.proto
In relation to: meshtastic/firmware#3053
Add Malaysia frequencies.
> Add Malaysia Frequency

- meshtastic/admin.options
- meshtastic/admin.proto
> Delete files admin message

- meshtastic/mesh.proto
> [CanaryOne Proposal](https://github.com/meshtastic/firmware/issues/3149)
> [CanaryOne Firmware PR](https://github.com/meshtastic/firmware/pull/3150)
> add CanaryOne to HardwareModel

- meshtastic/mesh.proto
Updated Heltec Tracker version names Related to [firmware/3163](https://github.com/meshtastic/firmware/pull/3163)
> divided heltec tracker 1.0 and 1.1

- meshtastic/deviceonly.proto
I haven't used this and I don't think anyone else does either.
> Deprecate DeviceState.no_save

- meshtastic/admin.proto
Turns out we need a way to actually set / unset it!
> Set / unset node to be favorited by nodenum

- meshtastic/mesh.proto
Adding new variant based on PROMICRO (NRF52) board
PR to firmware https://github.com/meshtastic/firmware/pull/3788
> New variant PROMICRO_DIY

- meshtastic/mesh.options
- meshtastic/mesh.proto
This will almost definitely need some subsequent changes, but this is the skeleton I plan to start throwing meat at
> Chunked payload for PoC binary transfer

- meshtastic/admin.proto
call this option with 0 to tare the scale, call it with a positive weight in kg to tell the calibration this weight is now on the scale
> add admin message for calibration.

- meshtastic/config.proto
Enables serial style logs over BLE characteristic
> BLE Device Logging

- meshtastic/mesh.options
- meshtastic/portnums.proto
- meshtastic/powermon.proto
These changes shouldn't break anything because they were not previously used.
> Add protobufs for forthcoming firmware and python PRs

- meshtastic/mesh.proto
> Add t1000-e hw model

- meshtastic/mesh.proto
for https://github.com/meshtastic/firmware/issues/4184
> Add new critical fault codes for flash corruption

- meshtastic/mesh.proto
Support for RadioMaster Bandit "Big Brother"
> New Device, RadioMaster Bandit

- meshtastic/mesh.proto
https://github.com/meshtastic/firmware/pull/4387
> Update mesh.proto add Minewsemi ME25LS01 LR1110 breakout ME25LE01_V1.0

- meshtastic/mesh.proto
Be available for M5 corebasic2.7、core2 Host machine
> Be available for  M5 corebasic2.7、core2

- meshtastic/mesh.proto
> heltec-wireless-bridge

- meshtastic/mesh.proto
Add support for M5Stack CoreS3 variant
[Related Issue](https://github.com/meshtastic/firmware/issues/4768)
> Add support for M5Stack CoreS3 variant

- meshtastic/mesh.proto
> feat: add seeed xiao s3

- meshtastic/config.proto
Required by https://github.com/meshtastic/firmware/pull/4951
> Add RegionCodes for Philippines

- meshtastic/telemetry.proto
See https://github.com/meshtastic/firmware/pull/4601/.
> Add CO2, SCD4X telemetry

- meshtastic/device_ui.proto
Swedish, Finnish, Polish, Turkish
> device-ui: more languages

- meshtastic/config.proto
because ERROR | ??:??:?? 71 [SerialModule] Unknown config type 10
> add device ui to config roll

- meshtastic/mesh.proto
Added Mesh_tab to HardwareModel as 86
https://github.com/valzzu/Mesh-Tab
> added Mesh-Tab 

- meshtastic/telemetry.proto
A high accuracy current and voltage sensor
related to: https://github.com/meshtastic/firmware/pull/5271
> Add INA226

- meshtastic/telemetry.proto
https://www.dfrobot.com/product-2689.html
> add dfrobot gravity rain gauge

- meshtastic/deviceonly.proto
Removed in:
https://github.com/meshtastic/firmware/pull/6116
> Deprecate did_gps_reset

- meshtastic/config.proto
change 0.pool.ntp.org to meshtastic.pool.ntp.org in NTP Server Commente
> Update NTP Server Comments

- meshtastic/device_ui.proto
That would be useful for https://github.com/meshtastic-ua project
> device_ui: add Ukrainian

- meshtastic/config.proto
> add existing 128x64 screen setting to protos

- meshtastic/mesh.proto
add Seeed solar node defination
> add seeed solar node defination

- meshtastic/telemetry.options
- meshtastic/telemetry.proto
Initial Linux Host Metrics telemetry packet type.
> Add Linux Host Metrics

- meshtastic/mesh.proto
> add T-Deck Pro and TLora Pager HW model IDs

- .github/pull_request_template.md
> should be from, not by

- meshtastic/mesh.proto
> add heltec v4 board.
